---
title: "DTW_KNN"
author: "David Ye"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# nuerons x neurons
load("adj_dtw.RData")
#dtw_Day_10
#dtw_Day_11
#dtw_Day_12
```

```{r}
plot(Food_Day_10[352,1,])
plot(Food_Day_10[1,1,])
```

```{r}
dtw_Day_10_non_zero <- dtw_Day_10


for (i in 1:nrow(dtw_Day_10)) {
  for (j in 1:ncol(dtw_Day_10)) {
    if(dtw_Day_10[i,j]==0) {
      dtw_Day_10_non_zero[i,j] <- 1
    }
  }
}

similarity <- 1/dtw_Day_10_non_zero
```

```{r}
# install.packages("igraph")
# library(igraph)
is_weighted(graph)
a <- similarity[1:10,1:10]
isSymmetric(similarity)
graph <- graph_from_adjacency_matrix(a, mode = "undirected",weighted = TRUE )
E(graph)$width<- E(graph)$weight
plot(graph)
```

```{r}
weighted_adj_matrix <- dtw_Day_10
degree_matrix <- diag(rowSums(dtw_Day_10))
laplacian <- degree_matrix - weighted_adj_matrix
lap_eigen <- eigen(laplacian)
smallest_eigens <- lap_eigen$vectors[,(length(lap_eigen$values)-4):length(lap_eigen$values)-1]
day_10_sc_kmeans <- kmeans(smallest_eigens, 15)
#day_10_sc_kmeans$cluster


```
```{r}
plot(smallest_eigens, col = day_10_sc_kmeans$cluster,xlim = c(0,0.01),ylim = c(0.2,-0.1))
points(day_10_sc_kmeans$centers, col = 1:15, pch = 8)
day_10_sc_kmeans$size
which(day_10_sc_kmeans$cluster==2)
plot(Food_Day_10[1,1,])
plot(Food_Day_10[58,1,])
plot(Food_Day_10[148,1,])
plot(Food_Day_10[7,1,])
plot(Food_Day_10[778,1,])
```