---
title: "Pre/Post Event Testing"
author: "David Ye"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
normalized_Day_10 <- normalize_avg(Food_Day_10)
dtw_Day_10 <- dtwDist(normalized_Day_10,normalized_Day_10)
```

```{r}
normalized_Day_11 <-normalize_avg(Shock_Day_11)
dtw_Day_11 <- dtwDist(normalized_Day_11,normalized_Day_11)
```

```{r}
normalized_Day_12 <-normalize_avg(Test_Day_12)
dtw_Day_12 <- dtwDist(normalized_Day_12,normalized_Day_12)
```

```{r}
#save(dtw_Day_10, dtw_Day_11, dtw_Day_12, file = "adj_dtw.RData")
save(dtw_Day_10, file = "adj_dtw.RData")

```

```{r}
normalize_avg <- function(object) {
  neurons <- length(object[,1,1])
  trials <- length(object[1,,1])
  timesteps <- length(object[1,1,])
  neuron_average <- matrix(NA, nrow = neurons, ncol = timesteps)
  ### normalize each trial then average them together
  for (i in 1:neurons) {
    sum <- rep(0, timesteps)
    for (j in 1:trials) {
      sum <- sum + (object[i,j,] - mean(object[i,j,]))/sd(object[i,j,])
    }
    neuron_average[i,] <- sum/trials
  }
  return (neuron_average)
}
```

```{r}
# dtw_dist <- function(avg_signals) {
#   neurons <- length(avg_signals[,1])
#   dtw_adj <- matrix(NA, nrow = neurons, ncol = neurons)
#   for (i in 1:neurons) {
#     for (j in 1:neurons) {
#       dtw_adj[i,j] <- as.numeric(dtw(i,j,distance.only = T)$distance)
#     }
#   }
#   return (dtw_adj)
# }

dtw_dist <- function(avg_signals) {
  return (dtwDist(avg_signals,avg_signals,distance.only = T))
}

```

```{r}
all_t_test <- function(object,tone = TRUE) {
  neurons <- length(object[,1,1])
  trials <- length(object[1,,1])
  all_tests <- matrix(NA, nrow = neurons, ncol = trials)
  for (i in 1:neurons) {
    for (j in 1:trials) {
      if (tone) {
        pre_tone <- object[i,j,100:300]
        post_tone <- object[i,j,301:400]
        all_tests[i,j] <- (t.test(x = post_tone,y = pre_tone,alternative =
                                         "greater", conf.level = 0.95)$p.value)
      }
      else {
        pre_food_shock <- object[i,j,301:429]
        post_food_shock <- object[430:550]
        all_tests[i,j] <- (t.test(x = post_food_shock,y = pre_food_shock,
                                     alternative = "greater", conf.level = 0.95)$p.value)
      }
    }
  }
  return (all_tests)
}
```

```{r}
all_Mann_Whitney_test <- function(object,tone = TRUE) {
  neurons <- length(object[,1,1])
  trials <- length(object[1,,1])
  all_tests <- matrix(NA, nrow = neurons, ncol = trials)
  for (i in 1:neurons) {
    for (j in 1:trials) {
      if (tone) {
        pre_tone <- object[i,j,100:300]
        post_tone <- object[i,j,301:400]
        all_tests[i,j] <- (wilcox.test(x = post_tone,y = pre_tone,alternative =
                                         "greater", conf.level = 0.95, paired = F)$p.value)
      }
      else {
        pre_food_shock <- object[i,j,301:429]
        post_food_shock <- object[430:550]
        all_tests[i,j] <- (wilcox.test(x = post_food_shock,y = pre_food_shock,
                                  alternative = "greater", conf.level = 0.95,
                                  paired = F)$p.value)
      }
    }
  }
  return (all_tests)
}
```

```{r}
day_10_tone_t_tests <- all_t_test(Food_Day_10,tone = T)
day_10_food_t_tests <- all_t_test(Food_Day_10,tone = F)
day_11_tone_t_tests <- all_t_test(Shock_Day_11,tone = T)
day_11_shock_t_tests <- all_t_test(Shock_Day_11,tone = F)
day_12_tone_t_tests <- all_t_test(Test_Day_12,tone = T)
save(day_10_tone_t_tests, day_10_food_t_tests, day_11_tone_t_tests, day_11_shock_t_tests, day_12_tone_t_tests,file = "t_test.RData")
```

```{r}
day_10_tone_MW_tests <- all_Mann_Whitney_test(Food_Day_10,tone = T)
day_10_food_MW_tests <- all_Mann_Whitney_test(Food_Day_10,tone = F)
day_11_tone_MW_tests <- all_Mann_Whitney_test(Shock_Day_11,tone = T)
day_11_shock_MW_tests <- all_Mann_Whitney_test(Shock_Day_11,tone = F)
day_12_tone_MW_tests <- all_Mann_Whitney_test(Test_Day_12,tone = T)
save(day_10_tone_MW_tests, day_10_food_MW_tests, day_11_tone_MW_tests, day_11_shock_MW_tests, day_12_tone_MW_tests,file = "MW_test.RData")
```
