---
title: "Processing_Raw_Data"
author: "David Ye"
date: "`r Sys.Date()`"
output: pdf_document
---

````{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggpubr)
```

```{r import data}
Food_Day_10_Read <- read.csv('Appetitive_Day_10.csv')
Shock_Day_11_Read <- read.csv('Aversive_Day_11.csv')
Test_Day_12_Read <- read.csv('Tone_only_test_Day_12.csv')
```

```{r creating 3D objects}
### remove row containing labels "both", "food", etc.
Food_Day_10 <- Food_Day_10_Read[-1,]
Shock_Day_11 <- Shock_Day_11_Read[-1,]
Test_Day_12 <- Test_Day_12_Read[-1,]
### group trials together
Food_Day_10 <- Food_Day_10[order(Food_Day_10$X),]
Shock_Day_11 <- Shock_Day_11[order(Shock_Day_11$X),]
Test_Day_12 <- Test_Day_12[order(Test_Day_12$X),]
### remove column containing trial numbers
Food_Day_10 <- Food_Day_10[,-1]
Shock_Day_11 <- Shock_Day_11[,-1]
Test_Day_12 <- Test_Day_12[,-1]
### convert dataframe to numerical matrix
Food_Day_10 <- as.matrix(sapply(Food_Day_10, as.numeric))
Shock_Day_11 <- as.matrix(sapply(Shock_Day_11, as.numeric))
Test_Day_12 <- as.matrix(sapply(Test_Day_12, as.numeric))
### remove rows containing NA
Food_Day_10 <- na.omit(Food_Day_10)
Shock_Day_11 <- na.omit(Shock_Day_11)
Test_Day_12 <- na.omit(Test_Day_12)
### transpose data into rows represent neurons
Food_Day_10 <- t(Food_Day_10)
Shock_Day_11 <- t(Shock_Day_11)
Test_Day_12 <- t(Test_Day_12)
### transform 2D array/matrix into 3D array/matrix
### of the shape (neurons, trials, time points)
Food_Day_10 <- array(Food_Day_10, dim = c(872,20,720)) #(872 neurons, 20 trials, 720 time points)
Shock_Day_11 <- array(Shock_Day_11, dim = c(519,10,598)) #(519 neurons, 10 trials, 598 time points)
Test_Day_12 <- array(Test_Day_12, dim = c(787,20,598)) #(787 neurons, 20 trials, 598 time points)
```

```{r}
save(Food_Day_10, Shock_Day_11, Test_Day_12, file = "3D_Activation_Object.RData")
```